name: Build

on: [push, pull_request]

jobs:
  test:
    services:
      mongodb:
        image: redis
        ports:
          - 6379:6379
          
    strategy:
      matrix:
        go-version: [1.12.x, ]
        platform: [ubuntu-latest, ]

    runs-on: ${{ matrix.platform }}

    env:
      GOPATH: ${{ github.workspace }}

    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 11.x

    - run: sudo apt update && sudo apt install build-essential libluajit-5.1-dev python3 python3-dev python3-pip
    - run: sudo pip install setuptools google protobuf grpcio

    - run: 'if [[ ! -f $CONSUL_DIR/consul ]]; then (mkdir -p "$CONSUL_DIR" && cd $CONSUL_DIR && wget https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_linux_amd64.zip && unzip consul_${CONSUL_VERSION}_linux_amd64.zip); fi'
      env:
        CONSUL_VERSION: 1.4.4
        CONSUL_DIR: $HOME/consul_$CONSUL_VERSION

    - run: $CONSUL_DIR/consul --version && $CONSUL_DIR/consul agent --dev &
      env:
        CONSUL_VERSION: 1.4.4
        CONSUL_DIR: $HOME/consul_$CONSUL_VERSION

    - run: sleep 5

    - name: Get tyk from source repository
      run: go get github.com/TykTechnologies/tyk/

    - name: Add current repository as fork remote
      run: git remote add fork https://github.com/${{ github.repository }}.git
      working-directory: ./src/github.com/TykTechnologies/tyk/

    - name: Fetch source from fork remote
      run: git fetch fork
      working-directory: ./src/github.com/TykTechnologies/tyk/

    - name: Checkout fork branch
      run: git checkout fork/${GITHUB_REF##*/}
      working-directory: ./src/github.com/TykTechnologies/tyk/

    - run: go get
      working-directory: ./src/github.com/TykTechnologies/tyk/

    - run: go install ./...
      working-directory: ./src/github.com/TykTechnologies/tyk/

    - run: go install ./vendor/{golang.org/x/tools/cmd/goimports,github.com/wadey/gocovmerge,github.com/mattn/goveralls}
      working-directory: ./src/github.com/TykTechnologies/tyk/

    - run: go get github.com/go-swagger/go-swagger/cmd/swagger
      working-directory: ./src/github.com/TykTechnologies/tyk/

    - name: Build coprocess lua
      run: go build -tags 'coprocess lua'
      working-directory: ./src/github.com/TykTechnologies/tyk/

    - run: sudo npm install -g api-spec-converter --unsafe-perm=true --allow-root

# Temporary skip tests
#    - name: Run tests
#      run: ./bin/ci-test.sh
#      working-directory: ./src/github.com/TykTechnologies/tyk/

    - name: Run build
      run: go build -v
      working-directory: ./src/github.com/TykTechnologies/tyk/

    - name: Upload Build
      uses: actions/upload-artifact@v1
      with:
        name: tyk-build
        path: ./src/github.com/TykTechnologies/tyk/tyk
