name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.15

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Get tyk from source repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: make install

      - name: Build tyk
        run: make build

      - name: Upload Build
        uses: actions/upload-artifact@v1
        with:
          name: tyk-build
          path: ./tyk
